version: '3.8'
services:
  app:
    container_name: api-parquimetro
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: postgres:5432
      POSTGRES_USERNAME: user
      POSTGRES_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: DEFAULT
      EMAIL_USER: postechchallenge@gmail.com
      EMAIL_PASSWORD: xmip tcir iyuq wbta
      TZ: "America/Fortaleza"
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: parquimetro
      TZ: "America/Fortaleza"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data