version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: parquimetro
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data