spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parquimetro
    username: user
    password: admin
  jpa:
    hibernate:
      format_sql: true
  mail:
    username: postechchallenge@gmail.com
    password: xmip tcir iyuq wbta
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    br.com.fiap.api_parquimetro: DEBUG