spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parquimetro
    username: user
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: postechchallenge@gmail.com
    password: Parquimetro@@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
